# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e30ab498678e8167de81268f84ed3891a5e33264674dc313f1bdd3fd03b4210a53aef567a8fa244518c69fb3c4ac7e872e312b7dd13dd28c7ab20792fecbfbf

test:
  secret_key_base: a62c4efbe27542be2b469933e1c489c03d8b0a5ef11b17b634727487af132450d395da570ba0ebae30a0e557bc02afe37318c47aba539f23d93604c2521e11ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
